In [1]:
import torch
import numpy as np
from torch.autograd import backward

In [2]:
x = torch.randn(2, 3, 4)    # (B, L, D)

x


tensor([[[ 0.6041,  0.9411, -1.9016,  1.2031],
         [ 0.0280,  1.0360,  0.8586, -0.2066],
         [-0.6958, -0.1157,  0.1734,  0.1943]],

        [[-0.5807,  2.5235,  1.7295, -0.1437],
         [-0.2297,  0.3453,  1.1387,  0.8787],
         [-0.2256, -0.1940,  0.3006,  0.2510]]])

创建一个tensor

In [3]:
# 1D tensor # 向量
t1 = torch.tensor([1, 2, 3])
print("1D tensor: \n", t1, t1.shape)

# 2D tensor # 行 * 列
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("\n2D tensor: \n", t2, t2.shape)

# 3D tensor # B, L, D
t3 = torch.tensor([[[1,2,3], [3,4,4]], [[5,6,5], [7,8,6]]])
print("\n3D tensor: \n", t3, t3.shape)

# from numpy
arr = np.array([1, 2, 3])
print("\nfrom numpy: \n", arr, arr.shape)
t_np = torch.tensor(arr)
print(t_np, t_np.shape)

1D tensor: 
 tensor([1, 2, 3]) torch.Size([3])

2D tensor: 
 tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])

3D tensor: 
 tensor([[[1, 2, 3],
         [3, 4, 4]],

        [[5, 6, 5],
         [7, 8, 6]]]) torch.Size([2, 2, 3])

from numpy: 
 [1 2 3] (3,)
tensor([1, 2, 3]) torch.Size([3])


支持bool类型，进行索引选择

In [4]:
x = torch.tensor([[1, 2, 3, 4, 5],[7,8,9,10,11]])
print(x,x.shape)
mask = x >2     # 生成bool索引
print(mask)

# bool索引进行筛选
# 本质是抽取所有满足条件的元素，并按一维返回
filtered_x = x[mask]
print(filtered_x, filtered_x.shape)

# 筛选并赋值
x[mask] = 0
print(x,x.shape)

tensor([[ 1,  2,  3,  4,  5],
        [ 7,  8,  9, 10, 11]]) torch.Size([2, 5])
tensor([[False, False,  True,  True,  True],
        [ True,  True,  True,  True,  True]])
tensor([ 3,  4,  5,  7,  8,  9, 10, 11]) torch.Size([8])
tensor([[1, 2, 0, 0, 0],
        [0, 0, 0, 0, 0]]) torch.Size([2, 5])


指定设备，默认是在cpu上

In [27]:
t_gpu = torch.tensor([1,2,3], device='cuda')
print(t_gpu)

tensor([1, 2, 3], device='cuda:0')


指定值/随机值填充，指定形状

In [32]:
shape = (2,3) # 指定形状

rand_tensor = torch.rand(shape)
print("\n从[0,1]均匀分布抽样的tensor：\n", rand_tensor, rand_tensor.shape)

randn_tensor = torch.randn(shape)
print("\n从标准正态分布抽样的tensor：\n", randn_tensor, randn_tensor.shape)

ones_tensor = torch.ones(shape)
print("\n值全为1的tensor：\n", ones_tensor, ones_tensor.shape)

zeros_tensor = torch.zeros(shape)
print("\n值全为0的tensor：\n", zeros_tensor, zeros_tensor.shape)

full_tensor = torch.full(shape, 2)
print("\n值全为指定值的tensor：\n", full_tensor, full_tensor.shape)


从[0,1]均匀分布抽样的tensor：
 tensor([[0.5706, 0.1379, 0.4771],
        [0.7786, 0.0218, 0.2077]]) torch.Size([2, 3])

从标准正态分布抽样的tensor：
 tensor([[-1.0413,  1.8681,  0.4926],
        [ 1.2051,  1.7713,  0.8027]]) torch.Size([2, 3])

值全为1的tensor：
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])

值全为0的tensor：
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.Size([2, 3])

值全为指定值的tensor：
 tensor([[2, 2, 2],
        [2, 2, 2]]) torch.Size([2, 3])


tensor 的属性

In [55]:
tensor = torch.rand(3, 4)

print(f"shape of tensor: {tensor.shape}")
print(f"data type of tensor: {tensor.dtype}")
print(f"device of tensor: {tensor.device}")

# 另外还有：requires_grad（是否求导），grad(梯度)

shape of tensor: torch.Size([3, 4])
data type of tensor: torch.float32
device of tensor: cpu


tensor 形状变换

In [38]:
# reshape() 元素个数需要一致，按元素顺序重新组织维度
x = torch.randn(4,4)
print(x, x.shape)
x = x.reshape(2,8)
print(x, x.shape)

tensor([[ 0.1924, -0.6655,  2.0167, -0.1813],
        [ 0.4229, -0.4074,  1.0733, -0.3020],
        [-0.2015, -0.5938,  0.0440,  0.2483],
        [ 1.0291, -0.9339,  0.4687, -1.1513]]) torch.Size([4, 4])
tensor([[ 0.1924, -0.6655,  2.0167, -0.1813,  0.4229, -0.4074,  1.0733, -0.3020],
        [-0.2015, -0.5938,  0.0440,  0.2483,  1.0291, -0.9339,  0.4687, -1.1513]]) torch.Size([2, 8])


In [43]:
# permute() 交换维度
# 原序列 x.shape=(2,3,4) 执行permute(1, 2, 0)后, (2,3,4)→(3,4,2)
# 新序列的每个元素 y[a,b,c] = x[c, a, b]
x = torch.tensor([[1,2,3], [4,5,6]])
x_reshape = x.reshape(3, 2)
x_transpose = x.permute(1, 0)   # 交换第0个和第1个维度。对于二维矩阵就是行列交换，进行装置
print("reshape:",x_reshape)
print("permute:",x_transpose)

reshape: tensor([[1, 2],
        [3, 4],
        [5, 6]])
permute: tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [46]:
# unsqueeze() 拓展维度，在指定位置插入一个长度为1的新维度
x = torch.tensor([[1,2,3], [4,5,6]])
print(x, x.shape)

# 扩展第0维
x_0 = x.unsqueeze(0)
print(x_0, x_0.shape)

# 扩展第1维
x_1 = x.unsqueeze(1)
print(x_1, x_1.shape)

# 扩展第2维
x_2 = x.unsqueeze(2)
print(x_2, x_2.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
tensor([[[1, 2, 3],
         [4, 5, 6]]]) torch.Size([1, 2, 3])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]]]) torch.Size([2, 3, 1])


In [50]:
# squeeze() 缩减大小为1的维度
x = torch.ones((1,1,3))
print(x, x.shape)

# 删除所有size=1的维度
y = x.squeeze()
print(y, y.shape)

# 删除指定维度，如果其size=1
z = x.squeeze(dim=0)
print(z, z.shape)

tensor([[[1., 1., 1.]]]) torch.Size([1, 1, 3])
tensor([1., 1., 1.]) torch.Size([3])
tensor([[1., 1., 1.]]) torch.Size([1, 3])


数学运算

In [54]:
a = torch.ones((2,3))
b = torch.ones((2,3))

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a @ b.t())

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[3., 3.],
        [3., 3.]])


统计函数

In [25]:
x = torch.tensor(
    [
        [1,3],
        [1,3],
        [1,3],
    ],
    dtype=torch.float,
)

print(x, x.shape, x.dtype)

# mean()只支持浮点数或复数类型,进行连续计算，而不能对long或者int离散型进行连续统计量计算
# tensor指定统计的维度，意味着要消灭这个维度
# 指定dim=0，意味着要消灭行维度，最后得到的统计量只有列维度
print(f"{x.mean()=}")
print(f"{x.mean(dim=0)=}")
print(f"{x.mean(dim=1)=}")

print()
# 指定参数keepdim=True，保留原来的维度不变，不会消灭统计的维度
mean = x.mean(dim=0)
print("dim=0, keepdim=false: ", mean, mean.shape)
mean = x.mean(dim=0, keepdim=True)
print("dim=0, keepdim=false: ", mean, mean.shape)

tensor([[1., 3.],
        [1., 3.],
        [1., 3.]]) torch.Size([3, 2]) torch.float32
x.mean()=tensor(2.)
x.mean(dim=0)=tensor([1., 3.])
x.mean(dim=1)=tensor([2., 2., 2.])

dim=0, keepdim=false:  tensor([1., 3.]) torch.Size([2])
dim=0, keepdim=false:  tensor([[1., 3.]]) torch.Size([1, 2])


索引和切片

In [35]:
x = torch.tensor([[1,2,3], [4,5,6]])
print("原始：", x, x.shape)

x1 = x[0, 1]
print("第一行第二个元素：", x1, x1.shape)

x2 = x[:, 1]
print("第二列：", x2, x2.shape)     # 切片中，:相当于保留维度，整数索引相当于该维度被消灭掉

x3 = x[1, :]
print("第二行：", x3, x3.shape)

x4 = x[:2, :]
print("前两行：", x4, x4.shape)

x5 = x[:, :2]
print("前两列：", x5, x5.shape)

原始： tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
第一行第二个元素： tensor(2) torch.Size([])
第二列： tensor([2, 5]) torch.Size([2])
第二行： tensor([4, 5, 6]) torch.Size([3])
前两行： tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
前两列： tensor([[1, 2],
        [4, 5]]) torch.Size([2, 2])


broadcasting 广播机制

In [39]:
# 让shape不同的张量从最后一维开始对齐，然后进行逐元素运算
# 不是复制数据，而是通过调整张量的索引方式（类似于reshape）
# 原则：
# 维度对齐：从最后一维度开始对齐，在短的tensor前面补1
# 扩展维度：在维度值为 1 的维度上，虚拟复制，让两个tensor纬度值一样
# 按位计算：两个tensor要么维度值一样，要么不同的维度值中有一个是1


x = torch.ones((1,2,3))
y = torch.ones((2,2,1))

print(x+y, (x+y).shape)

tensor([[[2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.]]]) torch.Size([2, 2, 3])


利用GPU加速计算

In [40]:
# 1.创建时，指定tensor的设备为 device="cuda"
# 2.将cpu上的tensor通过 to("cuda")方法转移到GPU上
# 3.通过 torch.cuda.is_available() 检查环境中是否有可能的cuda

import time

# 确保gpu可用
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"device: {device}")

# 生成随机矩阵
size = 10000
A_cpu = torch.rand(size, size)  # 默认在cpu上创建tensor
B_cpu = torch.rand(size, size)

# CPU上计算
start_cpu = time.time()
C_cpu = torch.mm(A_cpu, B_cpu)  # 矩阵乘法
end_cpu = time.time()
print(f"CPU time: {end_cpu-start_cpu:.6f} sec")

# GPU上计算
A_gpu = A_cpu.to(device)    # 将tensor转移到GPU上
B_gpu = B_cpu.to(device)

start_gpu = time.time()
C_gpu = torch.mm(A_gpu, B_gpu)
torch.cuda.synchronize()    # 等待GPU所有的核都完成计算
end_gpu = time.time()
print(f"GPU time: {end_gpu-start_gpu:.6f} sec")

device: cuda
CPU time: 2.183343 sec
GPU time: 0.342385 sec


自动求梯度

In [56]:
x = torch.tensor(1.0, requires_grad=True)   # 指定需要计算梯度
y = torch.tensor(1.0, requires_grad=True)

# v = 3*x + 4*y
# u = torch.square(v)
# z = torch.log(u)
z = ((3*x+4*y)**2).log()

z.backward()    # 反向传播求梯度：对标量 z 进行反向传播，计算所有参与计算的张量的梯度

print("x grad: ", x.grad)
print("y grad: ", y.grad)

x grad:  tensor(0.8571)
y grad:  tensor(1.1429)


线性回归

In [58]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 生成数据
inputs = torch.rand(100, 3) # 在均匀分布上生成shape为(100,3)的tensor
weights = torch.tensor([[1.1], [2.2], [3.3]])   # 预设的权重
bias = torch.tensor(4.4)    # 预设的bias
targets = inputs @ weights + bias + 0.1*torch.randn(100,1)  # 增加随机误差

# 随机初始化线性回归的参数
# 初始化参数直接放在cuda上，并启用梯度追踪
w = torch.rand((3, 1), device=device, requires_grad=True)
b = torch.rand((1,), device=device, requires_grad=True)

# 训练
# 将数据移至相同设备
inputs = inputs.to(device)
targets = targets.to(device)

epoch = 10000
lr = 3e-3

for i in range(epoch):
    outputs = inputs @ w + b
    loss = torch.mean(torch.square(outputs - targets))

    if i % 1000 == 0:
        print(f"epoch {i}, loss: {loss.item()}")

    loss.backward()

    with torch.no_grad():   # 参数更新部分，不需要追踪梯度
        w -= lr * w.grad
        b -= lr * b.grad

    # 清零梯度
    w.grad.zero_()
    b.grad.zero_()

print("训练后的权重w：\n", w)
print("训练后的偏置b：\n", b)

epoch 0, loss: 36.36445617675781
epoch 1000, loss: 0.08837786316871643
epoch 2000, loss: 0.04294818267226219
epoch 3000, loss: 0.023824023082852364
epoch 4000, loss: 0.01575198769569397
epoch 5000, loss: 0.012337286956608295
epoch 6000, loss: 0.010889985598623753
epoch 7000, loss: 0.01027537789195776
epoch 8000, loss: 0.01001384574919939
epoch 9000, loss: 0.009902318939566612
训练后的权重w：
 tensor([[1.1311],
        [2.1797],
        [3.2867]], device='cuda:0', requires_grad=True)
训练后的偏置b：
 tensor([4.4001], device='cuda:0', requires_grad=True)


loss 曲线: tensorboard 可视化训练过程

In [74]:
from torch.utils.tensorboard import SummaryWriter

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 生成数据
inputs = torch.rand(100, 3)
weights = torch.tensor([[1.1], [2.2], [3.3]])
bias = torch.tensor(4.4)
targets = inputs @ weights + bias + 0.1 * torch.randn(100, 1)

# ****************** 创建一个SummaryWriter实例 ******************
writer = SummaryWriter(log_dir="//torch/runs/exp1")

# 初始化参数时直接放在CUDA上，并启用梯度追踪
w = torch.rand(3, 1, requires_grad=True, device=device)
b = torch.rand(1, requires_grad=True, device=device)

# 将数据移至相同设备
inputs = inputs.to(device)
targets = targets.to(device)

epoch = 10000
lr = 0.003

for i in range(epoch):
    outputs = inputs @ w + b
    loss = torch.mean(torch.square(outputs - targets))
    if i % 1000 == 0:
        print(f"epoch {i}, loss: {loss.item()}")

    # ******************记录loss，三个参数分别：tag，loss值，第几步******************
    writer.add_scalar("loss/train", loss.item(), i)

    loss.backward()

    with torch.no_grad():  # 下边的计算不需要跟踪梯度
        w -= lr * w.grad
        b -= lr * b.grad

    # 清零梯度
    w.grad.zero_()
    b.grad.zero_()

writer.close()
print("训练后的权重 w:", w)
print("训练后的偏置 b:", b)

epoch 0, loss: 38.73357009887695
epoch 1000, loss: 0.06859183311462402
epoch 2000, loss: 0.03135785460472107
epoch 3000, loss: 0.01803194358944893
epoch 4000, loss: 0.013156084343791008
epoch 5000, loss: 0.01133759506046772
epoch 6000, loss: 0.010647943243384361
epoch 7000, loss: 0.010382214561104774
epoch 8000, loss: 0.010278185829520226
epoch 9000, loss: 0.010236723348498344
训练后的权重 w: tensor([[1.1496],
        [2.1548],
        [3.3964]], device='cuda:0', requires_grad=True)
训练后的偏置 b: tensor([4.3658], device='cuda:0', requires_grad=True)


In [ ]:
"""
我创建了一个新环境 tb_viewer 专门用来进行torch训练可视化
在这个环境里通过 pip install setuptools==68.2.2 降版本后跑通
"""